/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as academicLedgerV1BackupSol from "./AcademicLedger_v1_backup.sol";
export { AcademicLedger__factory } from "./AcademicLedger__factory";
