/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AcademicLedger {
  export type ContributionStruct = {
    contributor: AddressLike;
    cid: string;
    creditRole: string;
    timestamp: BigNumberish;
  };

  export type ContributionStructOutput = [
    contributor: string,
    cid: string,
    creditRole: string,
    timestamp: bigint
  ] & {
    contributor: string;
    cid: string;
    creditRole: string;
    timestamp: bigint;
  };

  export type ResearcherProfileStruct = {
    name: string;
    orcid: string;
    walletAddress: AddressLike;
    registeredAt: BigNumberish;
    exists: boolean;
  };

  export type ResearcherProfileStructOutput = [
    name: string,
    orcid: string,
    walletAddress: string,
    registeredAt: bigint,
    exists: boolean
  ] & {
    name: string;
    orcid: string;
    walletAddress: string;
    registeredAt: bigint;
    exists: boolean;
  };
}

export interface AcademicLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeCollaborator"
      | "getContributionCount"
      | "getContributions"
      | "getProfile"
      | "hasProfile"
      | "isAuthorized"
      | "logContribution"
      | "owner"
      | "registerProfile"
      | "researcherProfiles"
      | "revokeCollaborator"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollaboratorAuthorized"
      | "CollaboratorRevoked"
      | "ContributionLogged"
      | "ProfileRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeCollaborator",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributionCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributions",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logContribution",
    values: [string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerProfile",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "researcherProfiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCollaborator",
    values: [string, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeCollaborator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProfile", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "researcherProfiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCollaborator",
    data: BytesLike
  ): Result;
}

export namespace CollaboratorAuthorizedEvent {
  export type InputTuple = [projectId: string, collaborator: AddressLike];
  export type OutputTuple = [projectId: string, collaborator: string];
  export interface OutputObject {
    projectId: string;
    collaborator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollaboratorRevokedEvent {
  export type InputTuple = [projectId: string, collaborator: AddressLike];
  export type OutputTuple = [projectId: string, collaborator: string];
  export interface OutputObject {
    projectId: string;
    collaborator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionLoggedEvent {
  export type InputTuple = [
    projectId: string,
    contributor: AddressLike,
    cid: string,
    creditRole: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    projectId: string,
    contributor: string,
    cid: string,
    creditRole: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    projectId: string;
    contributor: string;
    cid: string;
    creditRole: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileRegisteredEvent {
  export type InputTuple = [
    wallet: AddressLike,
    name: string,
    orcid: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    name: string,
    orcid: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    name: string;
    orcid: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AcademicLedger extends BaseContract {
  connect(runner?: ContractRunner | null): AcademicLedger;
  waitForDeployment(): Promise<this>;

  interface: AcademicLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeCollaborator: TypedContractMethod<
    [projectId: string, collaborator: AddressLike],
    [void],
    "nonpayable"
  >;

  getContributionCount: TypedContractMethod<
    [projectId: string],
    [bigint],
    "view"
  >;

  getContributions: TypedContractMethod<
    [projectId: string],
    [AcademicLedger.ContributionStructOutput[]],
    "view"
  >;

  getProfile: TypedContractMethod<
    [wallet: AddressLike],
    [AcademicLedger.ResearcherProfileStructOutput],
    "view"
  >;

  hasProfile: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  isAuthorized: TypedContractMethod<
    [projectId: string, collaborator: AddressLike],
    [boolean],
    "view"
  >;

  logContribution: TypedContractMethod<
    [projectId: string, cid: string, creditRole: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerProfile: TypedContractMethod<
    [_name: string, _orcid: string],
    [void],
    "nonpayable"
  >;

  researcherProfiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, boolean] & {
        name: string;
        orcid: string;
        walletAddress: string;
        registeredAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  revokeCollaborator: TypedContractMethod<
    [projectId: string, collaborator: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeCollaborator"
  ): TypedContractMethod<
    [projectId: string, collaborator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getContributionCount"
  ): TypedContractMethod<[projectId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContributions"
  ): TypedContractMethod<
    [projectId: string],
    [AcademicLedger.ContributionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProfile"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [AcademicLedger.ResearcherProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasProfile"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAuthorized"
  ): TypedContractMethod<
    [projectId: string, collaborator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "logContribution"
  ): TypedContractMethod<
    [projectId: string, cid: string, creditRole: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerProfile"
  ): TypedContractMethod<[_name: string, _orcid: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "researcherProfiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, boolean] & {
        name: string;
        orcid: string;
        walletAddress: string;
        registeredAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeCollaborator"
  ): TypedContractMethod<
    [projectId: string, collaborator: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CollaboratorAuthorized"
  ): TypedContractEvent<
    CollaboratorAuthorizedEvent.InputTuple,
    CollaboratorAuthorizedEvent.OutputTuple,
    CollaboratorAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "CollaboratorRevoked"
  ): TypedContractEvent<
    CollaboratorRevokedEvent.InputTuple,
    CollaboratorRevokedEvent.OutputTuple,
    CollaboratorRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionLogged"
  ): TypedContractEvent<
    ContributionLoggedEvent.InputTuple,
    ContributionLoggedEvent.OutputTuple,
    ContributionLoggedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileRegistered"
  ): TypedContractEvent<
    ProfileRegisteredEvent.InputTuple,
    ProfileRegisteredEvent.OutputTuple,
    ProfileRegisteredEvent.OutputObject
  >;

  filters: {
    "CollaboratorAuthorized(string,address)": TypedContractEvent<
      CollaboratorAuthorizedEvent.InputTuple,
      CollaboratorAuthorizedEvent.OutputTuple,
      CollaboratorAuthorizedEvent.OutputObject
    >;
    CollaboratorAuthorized: TypedContractEvent<
      CollaboratorAuthorizedEvent.InputTuple,
      CollaboratorAuthorizedEvent.OutputTuple,
      CollaboratorAuthorizedEvent.OutputObject
    >;

    "CollaboratorRevoked(string,address)": TypedContractEvent<
      CollaboratorRevokedEvent.InputTuple,
      CollaboratorRevokedEvent.OutputTuple,
      CollaboratorRevokedEvent.OutputObject
    >;
    CollaboratorRevoked: TypedContractEvent<
      CollaboratorRevokedEvent.InputTuple,
      CollaboratorRevokedEvent.OutputTuple,
      CollaboratorRevokedEvent.OutputObject
    >;

    "ContributionLogged(string,address,string,string,uint256)": TypedContractEvent<
      ContributionLoggedEvent.InputTuple,
      ContributionLoggedEvent.OutputTuple,
      ContributionLoggedEvent.OutputObject
    >;
    ContributionLogged: TypedContractEvent<
      ContributionLoggedEvent.InputTuple,
      ContributionLoggedEvent.OutputTuple,
      ContributionLoggedEvent.OutputObject
    >;

    "ProfileRegistered(address,string,string,uint256)": TypedContractEvent<
      ProfileRegisteredEvent.InputTuple,
      ProfileRegisteredEvent.OutputTuple,
      ProfileRegisteredEvent.OutputObject
    >;
    ProfileRegistered: TypedContractEvent<
      ProfileRegisteredEvent.InputTuple,
      ProfileRegisteredEvent.OutputTuple,
      ProfileRegisteredEvent.OutputObject
    >;
  };
}
