/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AcademicLedger {
  export type ContributionStruct = {
    contributor: AddressLike;
    cid: string;
    creditRole: string;
    timestamp: BigNumberish;
  };

  export type ContributionStructOutput = [
    contributor: string,
    cid: string,
    creditRole: string,
    timestamp: bigint
  ] & {
    contributor: string;
    cid: string;
    creditRole: string;
    timestamp: bigint;
  };

  export type ProjectFinalizationStruct = {
    isFinalizationActive: boolean;
    finalizationDeadline: BigNumberish;
    isFinalized: boolean;
  };

  export type ProjectFinalizationStructOutput = [
    isFinalizationActive: boolean,
    finalizationDeadline: bigint,
    isFinalized: boolean
  ] & {
    isFinalizationActive: boolean;
    finalizationDeadline: bigint;
    isFinalized: boolean;
  };

  export type ResearcherProfileStruct = {
    name: string;
    orcid: string;
    walletAddress: AddressLike;
    registeredAt: BigNumberish;
    exists: boolean;
  };

  export type ResearcherProfileStructOutput = [
    name: string,
    orcid: string,
    walletAddress: string,
    registeredAt: bigint,
    exists: boolean
  ] & {
    name: string;
    orcid: string;
    walletAddress: string;
    registeredAt: bigint;
    exists: boolean;
  };
}

export interface AcademicLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_FINALIZATION_DURATION"
      | "MIN_FINALIZATION_DURATION"
      | "allProjects"
      | "authorizeCollaborator"
      | "authorizedCollaborators"
      | "checkIfDisputed"
      | "doesProjectExist"
      | "executeFinalization"
      | "flagContributionAsDisputed"
      | "getContributionCount"
      | "getContributions"
      | "getFinalizationStatus"
      | "getProfile"
      | "getProjectCollaborators"
      | "getUserProjects"
      | "haltFinalization"
      | "hasProfile"
      | "initializeProject"
      | "initiateFinalization"
      | "isAuthorized"
      | "isDisputed"
      | "isProjectAdmin"
      | "logContribution"
      | "owner"
      | "projectAdmins"
      | "projectCollaborators"
      | "projectFinalization"
      | "registerProfile"
      | "researcherProfiles"
      | "revokeCollaborator"
      | "syncUserProjects"
      | "transferProjectAdmin"
      | "userProjects"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollaboratorAuthorized"
      | "CollaboratorRevoked"
      | "ContributionDisputed"
      | "ContributionLogged"
      | "FinalizationExecuted"
      | "FinalizationHalted"
      | "FinalizationInitiated"
      | "ProfileRegistered"
      | "ProjectAdminTransferred"
      | "ProjectInitialized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_FINALIZATION_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_FINALIZATION_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allProjects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeCollaborator",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedCollaborators",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIfDisputed",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "doesProjectExist",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "executeFinalization",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "flagContributionAsDisputed",
    values: [string, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributionCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributions",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getFinalizationStatus",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectCollaborators",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserProjects",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "haltFinalization",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeProject",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateFinalization",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDisputed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProjectAdmin",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logContribution",
    values: [string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "projectAdmins",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "projectCollaborators",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectFinalization",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProfile",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "researcherProfiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCollaborator",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "syncUserProjects",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferProjectAdmin",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userProjects",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_FINALIZATION_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_FINALIZATION_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allProjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeCollaborator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCollaborators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIfDisputed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doesProjectExist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeFinalization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flagContributionAsDisputed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFinalizationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProjectCollaborators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserProjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "haltFinalization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateFinalization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isDisputed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isProjectAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectAdmins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectCollaborators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectFinalization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "researcherProfiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCollaborator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "syncUserProjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferProjectAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userProjects",
    data: BytesLike
  ): Result;
}

export namespace CollaboratorAuthorizedEvent {
  export type InputTuple = [projectId: string, collaborator: AddressLike];
  export type OutputTuple = [projectId: string, collaborator: string];
  export interface OutputObject {
    projectId: string;
    collaborator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollaboratorRevokedEvent {
  export type InputTuple = [projectId: string, collaborator: AddressLike];
  export type OutputTuple = [projectId: string, collaborator: string];
  export interface OutputObject {
    projectId: string;
    collaborator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionDisputedEvent {
  export type InputTuple = [
    projectId: string,
    contributionHash: BytesLike,
    reason: string
  ];
  export type OutputTuple = [
    projectId: string,
    contributionHash: string,
    reason: string
  ];
  export interface OutputObject {
    projectId: string;
    contributionHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionLoggedEvent {
  export type InputTuple = [
    projectId: string,
    contributor: AddressLike,
    cid: string,
    creditRole: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    projectId: string,
    contributor: string,
    cid: string,
    creditRole: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    projectId: string;
    contributor: string;
    cid: string;
    creditRole: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizationExecutedEvent {
  export type InputTuple = [projectId: string, timestamp: BigNumberish];
  export type OutputTuple = [projectId: string, timestamp: bigint];
  export interface OutputObject {
    projectId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizationHaltedEvent {
  export type InputTuple = [
    projectId: string,
    haltedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    projectId: string,
    haltedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    projectId: string;
    haltedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizationInitiatedEvent {
  export type InputTuple = [
    projectId: string,
    admin: AddressLike,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    projectId: string,
    admin: string,
    deadline: bigint
  ];
  export interface OutputObject {
    projectId: string;
    admin: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileRegisteredEvent {
  export type InputTuple = [
    wallet: AddressLike,
    name: string,
    orcid: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    name: string,
    orcid: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    name: string;
    orcid: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectAdminTransferredEvent {
  export type InputTuple = [
    projectId: string,
    previousAdmin: AddressLike,
    newAdmin: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    projectId: string,
    previousAdmin: string,
    newAdmin: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    projectId: string;
    previousAdmin: string;
    newAdmin: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectInitializedEvent {
  export type InputTuple = [
    projectId: string,
    admin: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    projectId: string,
    admin: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    projectId: string;
    admin: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AcademicLedger extends BaseContract {
  connect(runner?: ContractRunner | null): AcademicLedger;
  waitForDeployment(): Promise<this>;

  interface: AcademicLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_FINALIZATION_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_FINALIZATION_DURATION: TypedContractMethod<[], [bigint], "view">;

  allProjects: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  authorizeCollaborator: TypedContractMethod<
    [_projectId: string, _collaborator: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedCollaborators: TypedContractMethod<
    [arg0: string, arg1: AddressLike],
    [boolean],
    "view"
  >;

  checkIfDisputed: TypedContractMethod<
    [_projectId: string, _contributor: AddressLike, _timestamp: BigNumberish],
    [boolean],
    "view"
  >;

  doesProjectExist: TypedContractMethod<
    [_projectId: string],
    [boolean],
    "view"
  >;

  executeFinalization: TypedContractMethod<
    [_projectId: string],
    [void],
    "nonpayable"
  >;

  flagContributionAsDisputed: TypedContractMethod<
    [
      _projectId: string,
      _contributor: AddressLike,
      _timestamp: BigNumberish,
      _reason: string
    ],
    [void],
    "nonpayable"
  >;

  getContributionCount: TypedContractMethod<
    [_projectId: string],
    [bigint],
    "view"
  >;

  getContributions: TypedContractMethod<
    [_projectId: string],
    [AcademicLedger.ContributionStructOutput[]],
    "view"
  >;

  getFinalizationStatus: TypedContractMethod<
    [_projectId: string],
    [AcademicLedger.ProjectFinalizationStructOutput],
    "view"
  >;

  getProfile: TypedContractMethod<
    [_wallet: AddressLike],
    [AcademicLedger.ResearcherProfileStructOutput],
    "view"
  >;

  getProjectCollaborators: TypedContractMethod<
    [_projectId: string],
    [string[]],
    "view"
  >;

  getUserProjects: TypedContractMethod<
    [_user: AddressLike],
    [string[]],
    "view"
  >;

  haltFinalization: TypedContractMethod<
    [_projectId: string],
    [void],
    "nonpayable"
  >;

  hasProfile: TypedContractMethod<[_wallet: AddressLike], [boolean], "view">;

  initializeProject: TypedContractMethod<
    [_projectId: string],
    [void],
    "nonpayable"
  >;

  initiateFinalization: TypedContractMethod<
    [_projectId: string, _durationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  isAuthorized: TypedContractMethod<
    [_projectId: string, _collaborator: AddressLike],
    [boolean],
    "view"
  >;

  isDisputed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  isProjectAdmin: TypedContractMethod<
    [_projectId: string, _wallet: AddressLike],
    [boolean],
    "view"
  >;

  logContribution: TypedContractMethod<
    [_projectId: string, _cid: string, _creditRole: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  projectAdmins: TypedContractMethod<[arg0: string], [string], "view">;

  projectCollaborators: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [string],
    "view"
  >;

  projectFinalization: TypedContractMethod<
    [arg0: string],
    [
      [boolean, bigint, boolean] & {
        isFinalizationActive: boolean;
        finalizationDeadline: bigint;
        isFinalized: boolean;
      }
    ],
    "view"
  >;

  registerProfile: TypedContractMethod<
    [_name: string, _orcid: string],
    [void],
    "nonpayable"
  >;

  researcherProfiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, boolean] & {
        name: string;
        orcid: string;
        walletAddress: string;
        registeredAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  revokeCollaborator: TypedContractMethod<
    [_projectId: string, _collaborator: AddressLike],
    [void],
    "nonpayable"
  >;

  syncUserProjects: TypedContractMethod<
    [_user: AddressLike],
    [void],
    "nonpayable"
  >;

  transferProjectAdmin: TypedContractMethod<
    [_projectId: string, _newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  userProjects: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_FINALIZATION_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_FINALIZATION_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allProjects"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeCollaborator"
  ): TypedContractMethod<
    [_projectId: string, _collaborator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedCollaborators"
  ): TypedContractMethod<[arg0: string, arg1: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkIfDisputed"
  ): TypedContractMethod<
    [_projectId: string, _contributor: AddressLike, _timestamp: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "doesProjectExist"
  ): TypedContractMethod<[_projectId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "executeFinalization"
  ): TypedContractMethod<[_projectId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "flagContributionAsDisputed"
  ): TypedContractMethod<
    [
      _projectId: string,
      _contributor: AddressLike,
      _timestamp: BigNumberish,
      _reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getContributionCount"
  ): TypedContractMethod<[_projectId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContributions"
  ): TypedContractMethod<
    [_projectId: string],
    [AcademicLedger.ContributionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFinalizationStatus"
  ): TypedContractMethod<
    [_projectId: string],
    [AcademicLedger.ProjectFinalizationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProfile"
  ): TypedContractMethod<
    [_wallet: AddressLike],
    [AcademicLedger.ResearcherProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectCollaborators"
  ): TypedContractMethod<[_projectId: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserProjects"
  ): TypedContractMethod<[_user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "haltFinalization"
  ): TypedContractMethod<[_projectId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasProfile"
  ): TypedContractMethod<[_wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "initializeProject"
  ): TypedContractMethod<[_projectId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initiateFinalization"
  ): TypedContractMethod<
    [_projectId: string, _durationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAuthorized"
  ): TypedContractMethod<
    [_projectId: string, _collaborator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDisputed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProjectAdmin"
  ): TypedContractMethod<
    [_projectId: string, _wallet: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "logContribution"
  ): TypedContractMethod<
    [_projectId: string, _cid: string, _creditRole: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "projectAdmins"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "projectCollaborators"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "projectFinalization"
  ): TypedContractMethod<
    [arg0: string],
    [
      [boolean, bigint, boolean] & {
        isFinalizationActive: boolean;
        finalizationDeadline: bigint;
        isFinalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProfile"
  ): TypedContractMethod<[_name: string, _orcid: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "researcherProfiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, boolean] & {
        name: string;
        orcid: string;
        walletAddress: string;
        registeredAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeCollaborator"
  ): TypedContractMethod<
    [_projectId: string, _collaborator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "syncUserProjects"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferProjectAdmin"
  ): TypedContractMethod<
    [_projectId: string, _newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userProjects"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "CollaboratorAuthorized"
  ): TypedContractEvent<
    CollaboratorAuthorizedEvent.InputTuple,
    CollaboratorAuthorizedEvent.OutputTuple,
    CollaboratorAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "CollaboratorRevoked"
  ): TypedContractEvent<
    CollaboratorRevokedEvent.InputTuple,
    CollaboratorRevokedEvent.OutputTuple,
    CollaboratorRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionDisputed"
  ): TypedContractEvent<
    ContributionDisputedEvent.InputTuple,
    ContributionDisputedEvent.OutputTuple,
    ContributionDisputedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionLogged"
  ): TypedContractEvent<
    ContributionLoggedEvent.InputTuple,
    ContributionLoggedEvent.OutputTuple,
    ContributionLoggedEvent.OutputObject
  >;
  getEvent(
    key: "FinalizationExecuted"
  ): TypedContractEvent<
    FinalizationExecutedEvent.InputTuple,
    FinalizationExecutedEvent.OutputTuple,
    FinalizationExecutedEvent.OutputObject
  >;
  getEvent(
    key: "FinalizationHalted"
  ): TypedContractEvent<
    FinalizationHaltedEvent.InputTuple,
    FinalizationHaltedEvent.OutputTuple,
    FinalizationHaltedEvent.OutputObject
  >;
  getEvent(
    key: "FinalizationInitiated"
  ): TypedContractEvent<
    FinalizationInitiatedEvent.InputTuple,
    FinalizationInitiatedEvent.OutputTuple,
    FinalizationInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileRegistered"
  ): TypedContractEvent<
    ProfileRegisteredEvent.InputTuple,
    ProfileRegisteredEvent.OutputTuple,
    ProfileRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProjectAdminTransferred"
  ): TypedContractEvent<
    ProjectAdminTransferredEvent.InputTuple,
    ProjectAdminTransferredEvent.OutputTuple,
    ProjectAdminTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProjectInitialized"
  ): TypedContractEvent<
    ProjectInitializedEvent.InputTuple,
    ProjectInitializedEvent.OutputTuple,
    ProjectInitializedEvent.OutputObject
  >;

  filters: {
    "CollaboratorAuthorized(string,address)": TypedContractEvent<
      CollaboratorAuthorizedEvent.InputTuple,
      CollaboratorAuthorizedEvent.OutputTuple,
      CollaboratorAuthorizedEvent.OutputObject
    >;
    CollaboratorAuthorized: TypedContractEvent<
      CollaboratorAuthorizedEvent.InputTuple,
      CollaboratorAuthorizedEvent.OutputTuple,
      CollaboratorAuthorizedEvent.OutputObject
    >;

    "CollaboratorRevoked(string,address)": TypedContractEvent<
      CollaboratorRevokedEvent.InputTuple,
      CollaboratorRevokedEvent.OutputTuple,
      CollaboratorRevokedEvent.OutputObject
    >;
    CollaboratorRevoked: TypedContractEvent<
      CollaboratorRevokedEvent.InputTuple,
      CollaboratorRevokedEvent.OutputTuple,
      CollaboratorRevokedEvent.OutputObject
    >;

    "ContributionDisputed(string,bytes32,string)": TypedContractEvent<
      ContributionDisputedEvent.InputTuple,
      ContributionDisputedEvent.OutputTuple,
      ContributionDisputedEvent.OutputObject
    >;
    ContributionDisputed: TypedContractEvent<
      ContributionDisputedEvent.InputTuple,
      ContributionDisputedEvent.OutputTuple,
      ContributionDisputedEvent.OutputObject
    >;

    "ContributionLogged(string,address,string,string,uint256)": TypedContractEvent<
      ContributionLoggedEvent.InputTuple,
      ContributionLoggedEvent.OutputTuple,
      ContributionLoggedEvent.OutputObject
    >;
    ContributionLogged: TypedContractEvent<
      ContributionLoggedEvent.InputTuple,
      ContributionLoggedEvent.OutputTuple,
      ContributionLoggedEvent.OutputObject
    >;

    "FinalizationExecuted(string,uint256)": TypedContractEvent<
      FinalizationExecutedEvent.InputTuple,
      FinalizationExecutedEvent.OutputTuple,
      FinalizationExecutedEvent.OutputObject
    >;
    FinalizationExecuted: TypedContractEvent<
      FinalizationExecutedEvent.InputTuple,
      FinalizationExecutedEvent.OutputTuple,
      FinalizationExecutedEvent.OutputObject
    >;

    "FinalizationHalted(string,address,uint256)": TypedContractEvent<
      FinalizationHaltedEvent.InputTuple,
      FinalizationHaltedEvent.OutputTuple,
      FinalizationHaltedEvent.OutputObject
    >;
    FinalizationHalted: TypedContractEvent<
      FinalizationHaltedEvent.InputTuple,
      FinalizationHaltedEvent.OutputTuple,
      FinalizationHaltedEvent.OutputObject
    >;

    "FinalizationInitiated(string,address,uint256)": TypedContractEvent<
      FinalizationInitiatedEvent.InputTuple,
      FinalizationInitiatedEvent.OutputTuple,
      FinalizationInitiatedEvent.OutputObject
    >;
    FinalizationInitiated: TypedContractEvent<
      FinalizationInitiatedEvent.InputTuple,
      FinalizationInitiatedEvent.OutputTuple,
      FinalizationInitiatedEvent.OutputObject
    >;

    "ProfileRegistered(address,string,string,uint256)": TypedContractEvent<
      ProfileRegisteredEvent.InputTuple,
      ProfileRegisteredEvent.OutputTuple,
      ProfileRegisteredEvent.OutputObject
    >;
    ProfileRegistered: TypedContractEvent<
      ProfileRegisteredEvent.InputTuple,
      ProfileRegisteredEvent.OutputTuple,
      ProfileRegisteredEvent.OutputObject
    >;

    "ProjectAdminTransferred(string,address,address,uint256)": TypedContractEvent<
      ProjectAdminTransferredEvent.InputTuple,
      ProjectAdminTransferredEvent.OutputTuple,
      ProjectAdminTransferredEvent.OutputObject
    >;
    ProjectAdminTransferred: TypedContractEvent<
      ProjectAdminTransferredEvent.InputTuple,
      ProjectAdminTransferredEvent.OutputTuple,
      ProjectAdminTransferredEvent.OutputObject
    >;

    "ProjectInitialized(string,address,uint256)": TypedContractEvent<
      ProjectInitializedEvent.InputTuple,
      ProjectInitializedEvent.OutputTuple,
      ProjectInitializedEvent.OutputObject
    >;
    ProjectInitialized: TypedContractEvent<
      ProjectInitializedEvent.InputTuple,
      ProjectInitializedEvent.OutputTuple,
      ProjectInitializedEvent.OutputObject
    >;
  };
}
