/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as academicLedgerV1BackupSol from "./AcademicLedger_v1_backup.sol";
export type { academicLedgerV1BackupSol };
export type { AcademicLedger } from "./AcademicLedger";
export * as factories from "./factories";
export type { AcademicLedger } from "./AcademicLedger_v1_backup.sol/AcademicLedger";
export { AcademicLedger__factory } from "./factories/AcademicLedger_v1_backup.sol/AcademicLedger__factory";
