/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AcademicLedger } from "./AcademicLedger";
export * as factories from "./factories";
export { AcademicLedger__factory } from "./factories/AcademicLedger__factory";
